// lib/data.ts

export interface Property {
  id: string
  title: string
  price: string
  priceValue: number
  location: string
  area: string
  type: 'buy' | 'rent' | 'project'
  subtype?: 'new' | 'resell'          // new: builder/first-time sale | resell: owner/secondary sale
  category: 'Apartment' | 'Villa' | 'Plot' | 'Commercial' | 'Penthouse'
  bedrooms: number
  bathrooms: number
  status: 'Ready to Move' | 'Under Construction' | 'New Launch'
  badge?: string
  featured?: boolean
  gradientFrom: string
  gradientTo: string
  amenities: string[]
  description: string
  developer?: string
  possession?: string
  ownerName?: string                   // for resell: direct owner contact
  ownerSince?: string                  // how long owner has held
  ageOfProperty?: string              // for resell listings
  highlights: { label: string; value: string }[]
  floorPlans?: { name: string; area: string }[]
  slug: string
}

export const properties: Property[] = [
  {
    id: '1',
    slug: 'sky-residency-gomti-nagar',
    title: 'Sky Residency — 3BHK Premium',
    price: '₹1.25 Cr',
    priceValue: 12500000,
    location: 'Gomti Nagar, Lucknow',
    area: '1,850 sq.ft',
    type: 'buy',
    subtype: 'new',
    category: 'Apartment',
    bedrooms: 3,
    bathrooms: 2,
    status: 'Ready to Move',
    badge: 'Featured',
    featured: true,
    developer: 'Omaxe Group',
    gradientFrom: '#1e3a5f',
    gradientTo: '#2d6a8a',
    amenities: ['Swimming Pool', 'Gymnasium', 'Power Backup', '24/7 Security', 'Covered Parking', 'Club House', 'Kids Play Area', 'Jogging Track'],
    description: 'An exquisitely designed 3BHK apartment in the heart of Gomti Nagar. Featuring premium Italian marble flooring, modular kitchen with German fittings, and panoramic views of the city skyline. Located in a prestigious gated community with world-class amenities.',
    highlights: [
      { label: 'Area', value: '1,850 sq.ft' },
      { label: 'Floor', value: '12th Floor' },
      { label: 'Facing', value: 'East' },
      { label: 'Age', value: 'New Build' },
    ],
    floorPlans: [
      { name: '3BHK — Type A', area: '1,850 sq.ft' },
      { name: '3BHK — Type B', area: '2,100 sq.ft' },
      { name: '4BHK — Premium', area: '2,600 sq.ft' },
    ],
  },
  {
    id: '2',
    slug: 'serenity-villas-shaheed-path',
    title: 'Serenity Villa — Independent 4BHK',
    price: '₹2.8 Cr',
    priceValue: 28000000,
    location: 'Shaheed Path, Lucknow',
    area: '3,200 sq.ft',
    type: 'buy',
    subtype: 'resell',
    category: 'Villa',
    bedrooms: 4,
    bathrooms: 4,
    status: 'Ready to Move',
    badge: 'Hot Deal',
    featured: true,
    ownerName: 'Mr. Rajiv Sinha',
    ownerSince: '2018',
    ageOfProperty: '6 Years',
    gradientFrom: '#1a3a2a',
    gradientTo: '#2d5a3d',
    amenities: ['Private Garden', 'Home Theater', 'Smart Home', 'Generator', 'Modular Kitchen', 'Terrace Garden', 'Private Parking', 'CCTV'],
    description: 'A magnificent independent villa with lush private gardens and premium interiors crafted by award-winning designers. Experience the pinnacle of luxury living on Shaheed Path with complete privacy and exclusivity.',
    highlights: [
      { label: 'Plot Area', value: '3,200 sq.ft' },
      { label: 'Built-up', value: '2,800 sq.ft' },
      { label: 'Floors', value: 'G+2' },
      { label: 'Facing', value: 'North-East' },
    ],
    floorPlans: [
      { name: 'Ground Floor', area: '1,200 sq.ft' },
      { name: 'First Floor', area: '950 sq.ft' },
      { name: 'Terrace', area: '650 sq.ft' },
    ],
  },
  {
    id: '3',
    slug: 'promenade-hazratganj-2bhk',
    title: 'The Promenade — 2BHK City Living',
    price: '₹65,000/mo',
    priceValue: 65000,
    location: 'Hazratganj, Lucknow',
    area: '1,200 sq.ft',
    type: 'rent',
    category: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    status: 'Ready to Move',
    featured: true,
    gradientFrom: '#2a1a4a',
    gradientTo: '#4a2d6a',
    amenities: ['Fully Furnished', 'AC Rooms', 'Elevator', '24/7 Security', 'Covered Parking', 'Gym Access', 'Power Backup'],
    description: 'Fully furnished 2BHK apartment in the iconic Hazratganj area — Lucknow\'s cultural heart. Perfect for professionals and families seeking upscale city living with premium finishes and thoughtful design.',
    highlights: [
      { label: 'Area', value: '1,200 sq.ft' },
      { label: 'Floor', value: '5th Floor' },
      { label: 'Furnishing', value: 'Fully Furnished' },
      { label: 'Deposit', value: '2 months' },
    ],
  },
  {
    id: '4',
    slug: 'lakeside-residences-sultanpur-road',
    title: 'Lakeside Residences — New Launch',
    price: 'Starting ₹85 Lakh',
    priceValue: 8500000,
    location: 'Sultanpur Road, Lucknow',
    area: '1,450 sq.ft onwards',
    type: 'project',
    category: 'Apartment',
    bedrooms: 3,
    bathrooms: 2,
    status: 'New Launch',
    badge: 'New Launch',
    featured: true,
    gradientFrom: '#3d1f00',
    gradientTo: '#6b3a10',
    amenities: ['Lake View', 'Jogging Track', 'Kids Play Area', 'Yoga Deck', 'Multi-level Parking', 'Shopping Complex', 'EV Charging'],
    description: 'A landmark new launch project with stunning lake views. Thoughtfully designed residences with modern amenities in a tranquil setting. RERA approved. Book now at pre-launch prices.',
    developer: 'Omaxe Group',
    possession: 'Dec 2026',
    highlights: [
      { label: 'Units', value: '480 Units' },
      { label: 'Towers', value: '6 Towers' },
      { label: 'Possession', value: 'Dec 2026' },
      { label: 'RERA', value: 'UP/RERA/PRJ/2024' },
    ],
    floorPlans: [
      { name: '2BHK — Compact', area: '1,050 sq.ft' },
      { name: '3BHK — Standard', area: '1,450 sq.ft' },
      { name: '3BHK — Premium', area: '1,750 sq.ft' },
      { name: '4BHK — Luxury', area: '2,200 sq.ft' },
    ],
  },
  {
    id: '5',
    slug: 'golden-crest-penthouse',
    title: 'Golden Crest — Sky Penthouse',
    price: '₹4.5 Cr',
    priceValue: 45000000,
    location: 'Gomti Nagar Extension, Lucknow',
    area: '4,200 sq.ft',
    type: 'buy',
    subtype: 'new',
    category: 'Penthouse',
    bedrooms: 5,
    bathrooms: 5,
    status: 'Ready to Move',
    badge: 'Exclusive',
    developer: 'Prestige Estates',
    gradientFrom: '#2d1f00',
    gradientTo: '#5a3d0a',
    amenities: ['Private Rooftop Pool', 'Sky Terrace', 'Wine Cellar', 'Jacuzzi', 'Smart Home Automation', 'Private Elevator', 'Butler Service'],
    description: 'An ultra-luxury penthouse offering unparalleled 360° views of Lucknow\'s skyline. A masterpiece of architecture and design crafted for the most discerning buyer. The crown jewel of modern Lucknow real estate.',
    highlights: [
      { label: 'Area', value: '4,200 sq.ft' },
      { label: 'Floor', value: 'Top Floor (26th)' },
      { label: 'Private Terrace', value: '800 sq.ft' },
      { label: 'Car Parks', value: '3 Covered' },
    ],
    floorPlans: [
      { name: 'Living + Dining', area: '1,200 sq.ft' },
      { name: 'Master Suite', area: '650 sq.ft' },
      { name: 'Sky Terrace', area: '800 sq.ft' },
    ],
  },
  {
    id: '6',
    slug: 'prestige-heights-aliganj',
    title: 'Prestige Heights — 2BHK',
    price: '₹55 Lakh',
    priceValue: 5500000,
    location: 'Aliganj, Lucknow',
    area: '1,050 sq.ft',
    type: 'buy',
    subtype: 'resell',
    category: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    status: 'Ready to Move',
    ownerName: 'Mrs. Sunita Kapoor',
    ownerSince: '2022',
    ageOfProperty: '2 Years',
    gradientFrom: '#2a1020',
    gradientTo: '#5a2040',
    amenities: ['Power Backup', 'Covered Parking', 'Security', 'Elevator', 'Landscaped Garden', 'Water Purifier'],
    description: 'Affordable luxury in the well-connected Aliganj neighbourhood. A well-designed 2BHK with quality Italian finishes, modular kitchen, and all modern conveniences at an unbeatable price point.',
    highlights: [
      { label: 'Area', value: '1,050 sq.ft' },
      { label: 'Floor', value: '3rd Floor' },
      { label: 'Age', value: '2 Years' },
      { label: 'Facing', value: 'West' },
    ],
  },
  {
    id: '7',
    slug: 'corporate-suites-vibhuti-khand',
    title: 'Corporate Suites — Office Space',
    price: '₹95,000/mo',
    priceValue: 95000,
    location: 'Vibhuti Khand, Lucknow',
    area: '2,500 sq.ft',
    type: 'rent',
    category: 'Commercial',
    bedrooms: 0,
    bathrooms: 3,
    status: 'Ready to Move',
    gradientFrom: '#0a1a2a',
    gradientTo: '#1a3a5a',
    amenities: ['Conference Rooms', 'High-speed Fiber', 'Cafeteria', 'Covered Parking', 'Reception Desk', 'Server Room'],
    description: 'Premium commercial office space in the thriving Vibhuti Khand IT hub. Modern infrastructure with plug-and-play setup for growing businesses and MNCs looking for a prestigious Lucknow address.',
    highlights: [
      { label: 'Area', value: '2,500 sq.ft' },
      { label: 'Floor', value: '4th Floor' },
      { label: 'Type', value: 'Semi-Furnished' },
      { label: 'Deposit', value: '3 months' },
    ],
  },
  {
    id: '8',
    slug: 'green-valley-township-kanpur-road',
    title: 'Green Valley — Eco Township',
    price: 'Starting ₹45 Lakh',
    priceValue: 4500000,
    location: 'Kanpur Road, Lucknow',
    area: '1,100 sq.ft onwards',
    type: 'project',
    category: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    status: 'Under Construction',
    badge: 'Trending',
    gradientFrom: '#0a2a10',
    gradientTo: '#1a5020',
    amenities: ['EV Charging', 'Solar Power', 'Rainwater Harvesting', 'School', 'Hospital', 'Mall', 'Amphitheatre'],
    description: 'A sustainable eco-township with cutting-edge green features. Modern homes in a self-contained community with all social infrastructure. Live the future today with net-zero energy homes.',
    developer: 'ATS Group',
    possession: 'Mar 2027',
    highlights: [
      { label: 'Units', value: '1,200 Units' },
      { label: 'Towers', value: '12 Towers' },
      { label: 'Possession', value: 'Mar 2027' },
      { label: 'RERA', value: 'UP/RERA/PRJ/2024' },
    ],
    floorPlans: [
      { name: '1BHK — Studio', area: '650 sq.ft' },
      { name: '2BHK — Standard', area: '1,100 sq.ft' },
      { name: '3BHK — Premium', area: '1,500 sq.ft' },
    ],
  },

  // ── NEW PROPERTIES (Builder/First Sale) ──────────────────────────────────
  {
    id: '9',
    slug: 'elysian-heights-gomti-nagar-ext',
    title: 'Elysian Heights — 3BHK New Launch',
    price: 'Starting ₹92 Lakh',
    priceValue: 9200000,
    location: 'Gomti Nagar Extension, Lucknow',
    area: '1,650 sq.ft onwards',
    type: 'buy',
    subtype: 'new',
    category: 'Apartment',
    bedrooms: 3,
    bathrooms: 2,
    status: 'New Launch',
    badge: 'New Launch',
    featured: true,
    developer: 'Godrej Properties',
    possession: 'Jun 2027',
    gradientFrom: '#0a2030',
    gradientTo: '#1a4060',
    amenities: ['Sky Lounge', 'Infinity Pool', 'Yoga Studio', 'EV Charging', 'Smart Locks', 'Co-working Space', 'Kids Zone'],
    description: 'Godrej Properties proudly presents Elysian Heights — an iconic new residential tower in the fast-growing Gomti Nagar Extension. Offering smartly designed 3 & 4BHK homes with panoramic city views and curated lifestyle amenities at pre-launch pricing.',
    highlights: [
      { label: 'Units', value: '320 Units' },
      { label: 'Towers', value: '2 Towers (G+28)' },
      { label: 'Possession', value: 'Jun 2027' },
      { label: 'RERA', value: 'UP/RERA/PRJ/2025' },
    ],
    floorPlans: [
      { name: '3BHK — Compact', area: '1,650 sq.ft' },
      { name: '3BHK — Premium', area: '1,950 sq.ft' },
      { name: '4BHK — Luxury', area: '2,450 sq.ft' },
    ],
  },
  {
    id: '10',
    slug: 'signature-park-indira-nagar',
    title: 'Signature Park — 2BHK Ready',
    price: '₹68 Lakh',
    priceValue: 6800000,
    location: 'Indira Nagar, Lucknow',
    area: '1,150 sq.ft',
    type: 'buy',
    subtype: 'new',
    category: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    status: 'Ready to Move',
    badge: 'Featured',
    featured: true,
    developer: 'Eldeco Group',
    gradientFrom: '#1a2a0a',
    gradientTo: '#2d4a1a',
    amenities: ['Clubhouse', 'Badminton Court', 'Power Backup', 'Covered Parking', 'CCTV', 'Lift', 'Park'],
    description: 'Eldeco Signature Park offers brand-new 2BHK apartments with fresh possession available immediately. Enjoy the benefits of first ownership — clean interiors, builder warranty, and zero wear-and-tear. Located in the vibrant Indira Nagar locality.',
    highlights: [
      { label: 'Area', value: '1,150 sq.ft' },
      { label: 'Floor', value: '7th Floor' },
      { label: 'Facing', value: 'North' },
      { label: 'Age', value: 'Brand New' },
    ],
    floorPlans: [
      { name: '2BHK — Type A', area: '1,150 sq.ft' },
      { name: '2BHK — Type B', area: '1,280 sq.ft' },
    ],
  },
  {
    id: '11',
    slug: 'royal-arc-shaheed-path-new',
    title: 'Royal Arc — 4BHK Builder Floor',
    price: '₹1.65 Cr',
    priceValue: 16500000,
    location: 'Shaheed Path, Lucknow',
    area: '2,400 sq.ft',
    type: 'buy',
    subtype: 'new',
    category: 'Apartment',
    bedrooms: 4,
    bathrooms: 4,
    status: 'Ready to Move',
    badge: 'New',
    developer: 'Shalimar Corp',
    gradientFrom: '#1a0a2a',
    gradientTo: '#3a1a5a',
    amenities: ['Italian Marble Floors', 'Modular Kitchen', 'VRV AC', 'Private Terrace', 'Smart Home', '3 Car Parks', 'Intercom'],
    description: 'Straight from the builder — a premium 4BHK duplex apartment on Shaheed Path with ultra-luxury specifications. First-owner advantage: fresh OC, zero maintenance liability, full builder warranty on structure and fittings.',
    highlights: [
      { label: 'Area', value: '2,400 sq.ft' },
      { label: 'Floor', value: 'G+1 Duplex' },
      { label: 'Facing', value: 'East' },
      { label: 'Handover', value: 'Immediate' },
    ],
  },

  // ── RESELL PROPERTIES (Owner / Secondary Market) ──────────────────────────
  {
    id: '12',
    slug: 'heritage-towers-resell-gomti-nagar',
    title: 'Heritage Towers — Resale 3BHK',
    price: '₹78 Lakh',
    priceValue: 7800000,
    location: 'Gomti Nagar, Lucknow',
    area: '1,500 sq.ft',
    type: 'buy',
    subtype: 'resell',
    category: 'Apartment',
    bedrooms: 3,
    bathrooms: 2,
    status: 'Ready to Move',
    badge: 'Owner Direct',
    ownerName: 'Mr. Anil Verma',
    ownerSince: '2019',
    ageOfProperty: '5 Years',
    gradientFrom: '#2a0a1a',
    gradientTo: '#5a1a30',
    amenities: ['Fully Renovated', 'New Modular Kitchen', 'Swimming Pool', 'Club House', 'Power Backup', 'Covered Parking'],
    description: 'Resale 3BHK in the prestigious Heritage Towers society — directly from owner, no middlemen. The flat has been freshly renovated with new modular kitchen, Italian marble flooring, and modern bathrooms. Move in immediately. Motivated seller — price negotiable.',
    highlights: [
      { label: 'Area', value: '1,500 sq.ft' },
      { label: 'Floor', value: '8th Floor' },
      { label: 'Age', value: '5 Years' },
      { label: 'Renovation', value: '2024 (New)' },
    ],
  },
  {
    id: '13',
    slug: 'sunrise-apartments-resell-aliganj',
    title: 'Sunrise Apartments — Resale 2BHK',
    price: '₹48 Lakh',
    priceValue: 4800000,
    location: 'Aliganj, Lucknow',
    area: '980 sq.ft',
    type: 'buy',
    subtype: 'resell',
    category: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    status: 'Ready to Move',
    badge: 'Best Price',
    ownerName: 'Mrs. Kavita Sharma',
    ownerSince: '2016',
    ageOfProperty: '8 Years',
    gradientFrom: '#1a1a2a',
    gradientTo: '#2a2a5a',
    amenities: ['Well Maintained', 'Lift', 'Security', 'Parking', 'Gated Society', 'Garden', 'Water Supply 24/7'],
    description: 'Excellent resale deal in Aliganj\'s most established residential society. Owned by a single family for 8 years, well-maintained with regular upkeep. Perfect for first-time home buyers or investors seeking strong rental income. School, hospital, and market all within 500m.',
    highlights: [
      { label: 'Area', value: '980 sq.ft' },
      { label: 'Floor', value: '4th Floor' },
      { label: 'Age', value: '8 Years' },
      { label: 'Facing', value: 'South-West' },
    ],
  },
  {
    id: '14',
    slug: 'green-meadows-resell-villa',
    title: 'Green Meadows — Resale 3BHK Villa',
    price: '₹1.95 Cr',
    priceValue: 19500000,
    location: 'Shaheed Path, Lucknow',
    area: '2,800 sq.ft',
    type: 'buy',
    subtype: 'resell',
    category: 'Villa',
    bedrooms: 3,
    bathrooms: 3,
    status: 'Ready to Move',
    badge: 'Motivated Seller',
    ownerName: 'Col. R.K. Tiwari (Retd.)',
    ownerSince: '2017',
    ageOfProperty: '7 Years',
    gradientFrom: '#0a2a0a',
    gradientTo: '#1a5a1a',
    amenities: ['Vastu Compliant', 'Mature Garden', 'Solar Panels', 'RO Plant', 'Generator', 'Servant Quarters', 'Open Parking x3'],
    description: 'A beautifully maintained independent villa owned by a retired Colonel — immaculate condition with zero defects. Vastu-compliant layout, mature fruit-bearing garden, and fully automated security. Selling due to relocation. Open to serious buyers only.',
    highlights: [
      { label: 'Plot Area', value: '3,500 sq.ft' },
      { label: 'Built-up', value: '2,800 sq.ft' },
      { label: 'Age', value: '7 Years' },
      { label: 'Condition', value: 'Excellent' },
    ],
  },
  {
    id: '15',
    slug: 'pearl-residency-resell-indira-nagar',
    title: 'Pearl Residency — Resale 2BHK',
    price: '₹52 Lakh',
    priceValue: 5200000,
    location: 'Indira Nagar, Lucknow',
    area: '1,100 sq.ft',
    type: 'buy',
    subtype: 'resell',
    category: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    status: 'Ready to Move',
    ownerName: 'Mr. Suresh Pandey',
    ownerSince: '2020',
    ageOfProperty: '4 Years',
    gradientFrom: '#2a1a0a',
    gradientTo: '#5a3a1a',
    amenities: ['Semi-Furnished', 'Modular Kitchen', 'Power Backup', 'Elevator', 'Intercom', 'CCTV', 'Children Park'],
    description: 'A lightly used, semi-furnished 2BHK in the popular Pearl Residency society in Indira Nagar. Only 4 years old, well-maintained by owner. Comes with modular kitchen and wardrobes. Immediate possession. Loan pre-approved through HDFC, SBI, and ICICI.',
    highlights: [
      { label: 'Area', value: '1,100 sq.ft' },
      { label: 'Floor', value: '2nd Floor' },
      { label: 'Age', value: '4 Years' },
      { label: 'Furnishing', value: 'Semi-Furnished' },
    ],
  },
]

export const testimonials = [
  {
    id: 1,
    name: 'Rajesh Sharma',
    role: 'Software Engineer, TCS Lucknow',
    text: 'Fincap sol made our home-buying journey incredibly smooth. Their team understood exactly what we needed and found our dream apartment in Gomti Nagar within two weeks. The paperwork was handled flawlessly. Outstanding service!',
    rating: 5,
    location: 'Purchased 3BHK in Gomti Nagar',
    initials: 'RS',
  },
  {
    id: 2,
    name: 'Priya Verma',
    role: 'Business Owner, Lucknow',
    text: 'I was skeptical at first, but the team at Regalia exceeded all expectations. They guided me through every step of buying my first investment property and ensured the best deal. Truly professional, truly trustworthy advisors.',
    rating: 5,
    location: 'Invested in Sultanpur Road Project',
    initials: 'PV',
  },
  {
    id: 3,
    name: 'Dr. Arun & Deepti Mishra',
    role: 'Doctor Couple, KGMU',
    text: 'We found our perfect villa through Fincap sol. The entire process was completely transparent with zero hidden charges. Their legal team ensured everything was in perfect order. We couldn\'t be happier with our new home!',
    rating: 5,
    location: 'Purchased Villa on Shaheed Path',
    initials: 'AM',
  },
  {
    id: 4,
    name: 'Vikram Srivastava',
    role: 'Senior IAS Officer',
    text: 'Exceptional attention to detail and deep market knowledge that I haven\'t seen elsewhere. Fincap sol helped me identify the right property at the right price. Their negotiation skills alone saved me over 15 lakhs on my purchase.',
    rating: 5,
    location: 'Purchased Penthouse, Gomti Nagar Ext.',
    initials: 'VS',
  },
]

export const locations = [
  {
    name: 'Gomti Nagar',
    slug: 'gomti-nagar',
    properties: 142,
    avgPrice: '₹85 Lakh',
    priceChange: '+8.2%',
    type: 'Premium',
    description: 'The most prestigious residential area in Lucknow, known for wide roads, greenery, and upscale living.',
    gradient: 'from-blue-900 to-slate-700',
  },
  {
    name: 'Hazratganj',
    slug: 'hazratganj',
    properties: 67,
    avgPrice: '₹1.1 Cr',
    priceChange: '+5.1%',
    type: 'Prime',
    description: 'The cultural and commercial heart of Lucknow. Iconic address with unmatched connectivity.',
    gradient: 'from-purple-900 to-indigo-700',
  },
  {
    name: 'Shaheed Path',
    slug: 'shaheed-path',
    properties: 89,
    avgPrice: '₹1.5 Cr',
    priceChange: '+12.3%',
    type: 'Luxury',
    description: 'The fastest-growing luxury corridor. Home to Lucknow\'s most prestigious villas and gated communities.',
    gradient: 'from-emerald-900 to-teal-700',
  },
  {
    name: 'Aliganj',
    slug: 'aliganj',
    properties: 115,
    avgPrice: '₹55 Lakh',
    priceChange: '+6.4%',
    type: 'Mid-range',
    description: 'A well-established neighbourhood perfect for families, with excellent schools and social infrastructure.',
    gradient: 'from-rose-900 to-pink-700',
  },
  {
    name: 'Sultanpur Road',
    slug: 'sultanpur-road',
    properties: 203,
    avgPrice: '₹75 Lakh',
    priceChange: '+15.7%',
    type: 'Emerging',
    description: 'The most exciting growth corridor. New projects, modern townships, and huge investment potential.',
    gradient: 'from-orange-900 to-amber-700',
  },
  {
    name: 'Vibhuti Khand',
    slug: 'vibhuti-khand',
    properties: 88,
    avgPrice: '₹90 Lakh',
    priceChange: '+9.1%',
    type: 'Commercial',
    description: 'Lucknow\'s IT and business hub. Premium commercial spaces and residential apartments for professionals.',
    gradient: 'from-cyan-900 to-blue-700',
  },
]

export const developers = [
  { name: 'Omaxe Group', initials: 'OG' },
  { name: 'ATS Group', initials: 'AT' },
  { name: 'Godrej Properties', initials: 'GP' },
  { name: 'Prestige Estates', initials: 'PE' },
  { name: 'DLF Ltd.', initials: 'DL' },
  { name: 'Eldeco Group', initials: 'EG' },
  { name: 'Shalimar Corp', initials: 'SC' },
  { name: 'Supertech Ltd', initials: 'ST' },
]

export const stats = [
  { value: '2,500+', label: 'Properties Sold' },
  { value: '15+', label: 'Years Experience' },
  { value: '98%', label: 'Client Satisfaction' },
  { value: '₹500 Cr+', label: 'Deals Closed' },
]

export const whyChooseUs = [
  {
    icon: 'ShieldCheck',
    title: '100% Verified Listings',
    desc: 'Every property we list is rigorously verified by our expert team. Zero fraud, complete transparency — your trust is our foundation.',
  },
  {
    icon: 'TrendingUp',
    title: 'Market Intelligence',
    desc: 'With 15+ years in Lucknow real estate, we provide data-driven insights that help you make the smartest investment decisions.',
  },
  {
    icon: 'HandshakeIcon',
    title: 'End-to-End Support',
    desc: 'From property search to registration and beyond, our dedicated relationship managers guide you through every single step.',
  },
  {
    icon: 'Star',
    title: 'Premium Developer Network',
    desc: 'Access exclusive off-market deals and pre-launch prices through our unmatched network of top developers and builders.',
  },
]
